version: '3.8'

networks:
  testeVivoNetwork:
    external: true

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ZOO_ENABLE_AUTH=no
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - testeVivoNetwork

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9094:9094'
      - '9092:9092'
    environment:
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=LISTENER_FROM_HOST://localhost:9092,LISTENER_FROM_CONTAINER://kafka:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=LISTENER_FROM_HOST://localhost:9092,LISTENER_FROM_CONTAINER://kafka:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_FROM_HOST:PLAINTEXT,LISTENER_FROM_CONTAINER:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=LISTENER_FROM_CONTAINER
    networks:
      - testeVivoNetwork
    depends_on:
      - zookeeper
