version: '3.8'

networks:
  testeVivoNetwork:
    external: true

services:
  db:
    image: vivo-mock-db
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - testeVivoNetwork
  
  mock-api:
    image: metascale-api-mock-test
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/VivoTest
      - SPRING_DATASOURCE_PASSWORD=user
      - SPRING_DATASOURCE_USERNAME=user
    ports:
      - '3333:8080'
    expose:
      - '3333'
    depends_on:
      - db
    networks:
      - testeVivoNetwork