version: '3.8'

networks:
  testeVivoNetwork:
    external: true

services:
  db:
    image: mysql:8.0-debian
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - testeVivoNetwork
  
  connect:
    image: quay.io/debezium/connect:2.7
    restart: always
    environment:
      CONFIG_STORAGE_TOPIC: 'my_connect_configs'
      OFFSET_STORAGE_TOPIC: 'my_connect_offsets'
      STATUS_STORAGE_TOPIC: 'my_connect_statuses'
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 3
      BOOTSTRAP_SERVERS: "kafka:9094"
    ports:
      - '8083:8083'
    expose:
      - '8083'
    depends_on:
      - db
    networks:
      - testeVivoNetwork