version: '3.8'

networks:
  testeVivoNetwork:
    external: true

services:
  metascale-api:
    image: 'metascale:prod'
    ports:
      - '8080:8080'
    environment:
      - INSTANCE_TYPE=API
      - DEV_MODE=true
    networks:
      - testeVivoNetwork

  metascale-kafka:
    image: 'metascale:prod'
    environment:
      - INSTANCE_TYPE=KAFKA
      - KAFKA_BROKERS=kafka:9094
      - DEV_MODE=true
    networks:
      - testeVivoNetwork